version: 2.1

orbs:
  slack: circleci/slack@4.5.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - run:
          name: Install dependencies
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            export PATH=$HOME/.yarn/bin:$PATH
            yarn install
            yarn build
      - setup_remote_docker:
          docker_layer_caching: false
          version: 19.03.13
      - run:
          name: Build and push docker image
          command: |
            DOCKER_STR="${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${DOCKER_REPO}"
            TAG="${DOCKER_STR}:${CIRCLE_BUILD_NUM}"
            docker build -t ${TAG} .
            docker tag ${TAG} ${DOCKER_STR}:latest
            docker login -u ${DOCKER_ALI_USERNAME} -p ${DOCKER_ALI_PWD} ${DOCKER_REGISTRY}
            docker push ${TAG}
            docker push ${DOCKER_STR}:latest
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main