version: 2.1

orbs:
  slack: circleci/slack@4.5.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Remove node
          command: |
            sudo apt remove nodejs npm
            sudo rm -rf /usr/local/lib/node*
            sudo rm -rf /usr/local/include/node*
            sudo rm -rf /usr/local/bin/node*
            sudo rm -rf /usr/local/bin/npm*
      - run:
          name: Install node
          command: |
            curl -O https://nodejs.org/dist/v20.9.0/node-v20.9.0-linux-x64.tar.xz
            tar -xvf node-v20.9.0-linux-x64.tar.xz
            sudo mv node-v20.9.0-linux-x64 /usr/local/node
            sudo ln -s /usr/local/node/bin/node /usr/local/bin/node
            sudo ln -s /usr/local/node/bin/npm /usr/local/bin/npm
            node --version
            npm --version
            sudo npm install -g yarn
            yarn --version
      - run:
          name: Install dependencies
          command: |
            yarn install
            yarn build
      - setup_remote_docker:
          docker_layer_caching: false
          version: 19.03.13
      - run:
          name: Build and push docker image
          command: |
            DOCKER_STR="${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${DOCKER_REPO}"
            TAG="${DOCKER_STR}:${CIRCLE_BUILD_NUM}"
            docker build -t ${TAG} .
            docker tag ${TAG} ${DOCKER_STR}:latest
            docker login -u ${DOCKER_ALI_USERNAME} -p ${DOCKER_ALI_PWD} ${DOCKER_REGISTRY}
            docker push ${TAG}
            docker push ${DOCKER_STR}:latest
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main